version: '2'

services:
  app:
    image: node:latest
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install --silent && npm run dev"
    ports:
      - "3000:3000"
